site_name: My Docs

theme:
  name: material

  font:
    text: Noto Sans JP
    code: Inconsolata

  palette:
    - scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.tabs.sticky

  custom_dir: overrides

plugins:
  search:
    lang: 'ja'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/Ramajan_
      name: Ramajan_ on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/Mannnenn/nokolat2024
  comments: true

repo_url: https://github.com/Mannnenn/nokolat2024
repo_name: Mannnenn/nokolat2024

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_javascript:
  - https://giscus.app/client.js

extra_css:
  - stylesheets/extra.css
